# Project-wide Gradle settings
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official

# Improve build performance
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.workers.max=8

# Android Gradle Plugin Options
android.lint.missingDimensionStrategy=store

# Disable telemetry
android.gradle.disableInjectionConfigs=true
